version = 0.1
[default.deploy.parameters]
stack_name = "EmailForwarding"
s3_prefix = "EmailForwarding"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
tags = "app=EmailForwarding"
